import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/features/components/layout/Navbar";
import ThemeProvider from "@/features/context/themeContext";
import AuthProvider from "@/features/context/authContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Shop-Swift",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <head>
                    <script
                        dangerouslySetInnerHTML={{
                            __html: `
                            (function() {
                                try {
                                    var theme = localStorage.getItem('theme');
                                    if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                                        document.documentElement.classList.add('dark');
                                    }
                                } catch (e) {}
                            })();
                        `,
                        }}
                    />
                </head>
                <ThemeProvider>
                    <AuthProvider>
                        <Navbar />
                        <main className="bg-white/80 dark:bg-neutral-900/100 flex-1">
                            {children}
                        </main>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
