import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/features/components/layout/Navbar";
import ThemeProvider from "@/features/context/themeContext";
import AuthProvider from "@/features/context/authContext";
import CartProvider from "@/features/context/cartContext";
import "../globals.css";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Shop-Swift",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) notFound();

    setRequestLocale(locale);

    return (
        <html
            lang={locale}
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <NextIntlClientProvider>
                    <ThemeProvider>
                        <AuthProvider>
                            <CartProvider>
                                <Navbar />
                                <main className="bg-white/80 dark:bg-neutral-900/100 flex-1">
                                    {children}
                                </main>
                            </CartProvider>
                        </AuthProvider>
                    </ThemeProvider>{" "}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
